name: Purge
version: '${project.version}'
main: cyci.org.phil.purge.Purge
api-version: 1.19
depend:
  - TitleManager
  - Vault
  - LuckPerms
softdepend:
  - MicroLib
authors: [ Phil0004 ]
description: Minecraft plugin to introduce the purge
website: cyci.org

commands:
  test:
    usage: /test
    description: Test command for the purge gamemode
    permission: purge.commands.test

