name: Purge
version: '${project.version}'
main: org.cyci.phil.purge.Purge
api-version: 1.19
depend:
  - Vault
  - LuckPerms
  - PlaceholderAPI
softdepend:
  - MicroLib
authors: [ Phil0004 ]
description: Minecraft plugin to introduce the purge
website: cyci.org

commands:
  purge:
    usage: /purge
    description: Main purge command
    permission: purge.commands.purge

